### PR TITLE
Add in queue system

### PR DESCRIPTION
**Pull request by logicalmechanism**
This branch will include additional fixes for the aiken contracts as well as the decentralized queue for processing orders.

### CODE REVIEW

**Comment by logicalmechanism** [comment]
The assist lib and contracts must be updated to 1.0.7 aiken and 1.1.0 stdlib. The current build is forcing the 1.0.6 aiken and 1.0.0 stdlib. The change includes a lot of breaking changes so I need to take a step back and fix some things.

**Comment by logicalmechanism** [comment]
branching off here to attempt to model a multi-element queue

**Comment by logicalmechanism** [comment]
sale works, queue works, and there is a batcher

**Comment by logicalmechanism** [comment]
The contracts should have the correct cip68 prefixes now.

**Review by AndrewWestberg — APPROVED** [review]

**Pull request merged**
